import type { Company } from "./types";

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "TechViet Solutions",
    field: "Phát triển phần mềm",
    logo: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=80&h=80&fit=crop&crop=center",
    location: "Hà Nội",
    employees: "200+",
    employeeCount: 200,
    rating: 4.8,
    reviews: 120,
    description:
      "Công ty hàng đầu về giải pháp phần mềm doanh nghiệp với hơn 10 năm kinh nghiệm trong ngành công nghệ thông tin.",
    founded: 2013,
    website: "techviet.com",
    isVerified: true,
    openPositions: 15,
    benefits: ["Bảo hiểm sức khỏe", "Thưởng hiệu suất", "Du lịch công ty"],
    workingHours: "8:00 - 17:30",
    companyType: "Enterprise",
  },
  {
    id: "2",
    name: "AI Innovation Hub",
    field: "Trí tuệ nhân tạo",
    logo: "https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=80&h=80&fit=crop&crop=center",
    location: "TP.HCM",
    employees: "150+",
    employeeCount: 150,
    rating: 4.9,
    reviews: 85,
    description:
      "Chuyên gia về AI và Machine Learning, phát triển các sản phẩm công nghệ tiên tiến cho thị trường toàn cầu.",
    founded: 2018,
    website: "aiinnovation.vn",
    isVerified: true,
    openPositions: 8,
    benefits: ["Flexible working", "Stock options", "Learning budget"],
    workingHours: "9:00 - 18:00",
    companyType: "Startup",
  },
  {
    id: "3",
    name: "Mobile First Co.",
    field: "Mobile App Development",
    logo: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=80&h=80&fit=crop&crop=center",
    location: "Đà Nẵng",
    employees: "80+",
    employeeCount: 80,
    rating: 4.7,
    reviews: 95,
    description:
      "Startup năng động chuyên phát triển ứng dụng di động cho các doanh nghiệp lớn và startup công nghệ.",
    founded: 2020,
    website: "mobilefirst.vn",
    isVerified: false,
    openPositions: 12,
    benefits: ["Remote work", "Team building", "Overtime pay"],
    workingHours: "8:30 - 17:30",
    companyType: "SME",
  },
  {
    id: "4",
    name: "CloudTech Vietnam",
    field: "Cloud Computing",
    logo: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=80&h=80&fit=crop&crop=center",
    location: "Hà Nội",
    employees: "300+",
    employeeCount: 300,
    rating: 4.6,
    reviews: 150,
    description:
      "Nhà cung cấp dịch vụ cloud hàng đầu Việt Nam với giải pháp toàn diện cho doanh nghiệp và tổ chức.",
    founded: 2015,
    website: "cloudtech.vn",
    isVerified: true,
    openPositions: 20,
    benefits: ["13th month salary", "Training courses", "Health insurance"],
    workingHours: "8:00 - 17:00",
    companyType: "Enterprise",
  },
  {
    id: "5",
    name: "CyberSec Pro",
    field: "An ninh mạng",
    logo: "https://images.unsplash.com/photo-1553484771-371a605b060b?w=80&h=80&fit=crop&crop=center",
    location: "TP.HCM",
    employees: "120+",
    employeeCount: 120,
    rating: 4.8,
    reviews: 75,
    description:
      "Chuyên gia bảo mật thông tin và an ninh mạng cho các tổ chức lớn, ngân hàng và doanh nghiệp tài chính.",
    founded: 2017,
    website: "cybersecpro.vn",
    isVerified: true,
    openPositions: 6,
    benefits: ["High salary", "Certification support", "Flexible hours"],
    workingHours: "9:00 - 18:00",
    companyType: "SME",
  },
  {
    id: "6",
    name: "DataViz Analytics",
    field: "Data Analytics",
    logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=80&h=80&fit=crop&crop=center",
    location: "Đà Nẵng",
    employees: "60+",
    employeeCount: 60,
    rating: 4.5,
    reviews: 45,
    description:
      "Công ty chuyên về phân tích dữ liệu và business intelligence cho doanh nghiệp trong và ngoài nước.",
    founded: 2019,
    website: "dataviz.vn",
    isVerified: false,
    openPositions: 4,
    benefits: ["Work from home", "Performance bonus", "Team events"],
    workingHours: "8:30 - 17:30",
    companyType: "Startup",
  },
];

export const fields = [
  "Tất cả",
  "Phát triển phần mềm",
  "Trí tuệ nhân tạo",
  "Mobile App Development",
  "Cloud Computing",
  "An ninh mạng",
  "Data Analytics",
];
export const locations = ["Tất cả", "Hà Nội", "TP.HCM", "Đà Nẵng"];
export const companySizes = ["Tất cả", "1-50", "51-100", "101-200", "200+"];
export const companyTypes = ["Tất cả", "Startup", "SME", "Enterprise", "MNC"];
