import type { Professional } from "./types";

export const mockProfessionals: Professional[] = [
  {
    id: "1",
    name: "Nguyễn Thành Đạt",
    title: "Senior Full-stack Developer",
    avatar:
      "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop",
    location: "Hồ Chí Minh",
    hourlyRate: 800000,
    rating: 4.9,
    reviewCount: 127,
    skills: [
      { name: "ReactJS", level: "Chuyên gia" },
      { name: "NodeJS", level: "Chuyên gia" },
      { name: "MongoDB", level: "Giỏi" },
      { name: "TypeScript", level: "Giỏi" },
    ],
    availability: "available",
    completedProjects: 89,
    description:
      "Chuyên gia phát triển ứng dụng web với 8+ năm kinh nghiệm. Đã hoàn thành 200+ dự án thành công cho các startup và doanh nghiệp lớn.",
    isOnline: true,
    experience: 8,
    category: "Web Development",
    languages: ["Tiếng Việt", "English"],
    certifications: ["AWS Certified", "React Certified"],
    responseTime: "< 1 giờ",
    successRate: 98,
  },
  {
    id: "2",
    name: "Trần Minh Anh",
    title: "Mobile App Developer",
    avatar:
      "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop",
    location: "Hà Nội",
    hourlyRate: 750000,
    rating: 4.8,
    reviewCount: 89,
    skills: [
      { name: "Flutter", level: "Chuyên gia" },
      { name: "React Native", level: "Giỏi" },
      { name: "Firebase", level: "Chuyên gia" },
      { name: "Kotlin", level: "Khá" },
    ],
    availability: "busy",
    completedProjects: 65,
    description:
      "Chuyên gia phát triển ứng dụng di động cross-platform. Tập trung vào UX/UI và performance optimization cho mobile apps.",
    isOnline: false,
    experience: 6,
    category: "Mobile Development",
    languages: ["Tiếng Việt", "English", "日本語"],
    certifications: ["Google Flutter Certified"],
    responseTime: "< 2 giờ",
    successRate: 95,
  },
  {
    id: "3",
    name: "Lê Hoàng Nam",
    title: "DevOps Engineer",
    avatar:
      "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop",
    location: "Đà Nẵng",
    hourlyRate: 900000,
    rating: 4.9,
    reviewCount: 156,
    skills: [
      { name: "AWS", level: "Chuyên gia" },
      { name: "Docker", level: "Chuyên gia" },
      { name: "Kubernetes", level: "Giỏi" },
      { name: "Terraform", level: "Giỏi" },
    ],
    availability: "available",
    completedProjects: 112,
    description:
      "Chuyên gia DevOps với kinh nghiệm triển khai hệ thống cloud-native. Đảm bảo tính ổn định và bảo mật cho infrastructure.",
    isOnline: true,
    experience: 10,
    category: "DevOps",
    languages: ["Tiếng Việt", "English"],
    certifications: ["AWS Solutions Architect", "Kubernetes Certified"],
    responseTime: "< 30 phút",
    successRate: 99,
  },
  {
    id: "4",
    name: "Phạm Thị Lan",
    title: "UI/UX Designer",
    avatar:
      "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop",
    location: "Hồ Chí Minh",
    hourlyRate: 600000,
    rating: 4.7,
    reviewCount: 73,
    skills: [
      { name: "Figma", level: "Chuyên gia" },
      { name: "Adobe XD", level: "Giỏi" },
      { name: "Sketch", level: "Giỏi" },
      { name: "Prototyping", level: "Chuyên gia" },
    ],
    availability: "available",
    completedProjects: 45,
    description:
      "Designer chuyên về UX/UI với passion tạo ra những trải nghiệm người dùng tuyệt vời. Có kinh nghiệm với các startup và enterprise.",
    isOnline: true,
    experience: 5,
    category: "UI/UX Design",
    languages: ["Tiếng Việt", "English"],
    certifications: ["Google UX Design Certificate"],
    responseTime: "< 1 giờ",
    successRate: 96,
  },
  {
    id: "5",
    name: "Võ Minh Tuấn",
    title: "Python Backend Developer",
    avatar:
      "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop",
    location: "Cần Thơ",
    hourlyRate: 700000,
    rating: 4.8,
    reviewCount: 94,
    skills: [
      { name: "Python", level: "Chuyên gia" },
      { name: "Django", level: "Chuyên gia" },
      { name: "PostgreSQL", level: "Giỏi" },
      { name: "Redis", level: "Giỏi" },
    ],
    availability: "available",
    completedProjects: 78,
    description:
      "Backend developer chuyên Python với kinh nghiệm xây dựng API và microservices. Đam mê clean code và system architecture.",
    isOnline: false,
    experience: 7,
    category: "Backend Development",
    languages: ["Tiếng Việt", "English"],
    certifications: ["Python Institute Certified"],
    responseTime: "< 3 giờ",
    successRate: 97,
  },
  {
    id: "6",
    name: "Đặng Thị Mai",
    title: "QA Engineer",
    avatar:
      "https://images.pexels.com/photos/1181424/pexels-photo-1181424.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop",
    location: "Hà Nội",
    hourlyRate: 550000,
    rating: 4.6,
    reviewCount: 67,
    skills: [
      { name: "Selenium", level: "Chuyên gia" },
      { name: "Cypress", level: "Giỏi" },
      { name: "Jest", level: "Giỏi" },
      { name: "Manual Testing", level: "Chuyên gia" },
    ],
    availability: "busy",
    completedProjects: 52,
    description:
      "QA Engineer với kinh nghiệm automation testing và manual testing. Đảm bảo chất lượng sản phẩm với test coverage cao.",
    isOnline: true,
    experience: 4,
    category: "Testing/QA",
    languages: ["Tiếng Việt", "English"],
    certifications: ["ISTQB Certified"],
    responseTime: "< 2 giờ",
    successRate: 94,
  },
];

export const categories = [
  "Tất cả",
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "DevOps",
  "Backend Development",
  "Testing/QA",
];
export const locations = [
  "Tất cả",
  "Hồ Chí Minh",
  "Hà Nội",
  "Đà Nẵng",
  "Cần Thơ",
];
export const experienceLevels = [
  "Tất cả",
  "1-3 năm",
  "3-5 năm",
  "5-8 năm",
  "8+ năm",
];
